"""add_link_column_to_quote_table

Revision ID: manual_001_add_link_to_quote
Revises: e0fb392ca490
Create Date: 2025-06-05 18:00:00.000000
# Using a fixed date for consistency in manual creation

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "manual_001_add_link_to_quote"
down_revision: str | None = "e0fb392ca490"  # Points to the initial setup migration
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually adding the column 'link' to the 'quote' table
    op.add_column("quote", sa.Column("link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually dropping the column 'link' from the 'quote' table
    op.drop_column("quote", "link")
    # ### end Alembic commands ###
